taskfiles(test): run integration tests package by package

diff --git a/taskfiles/test.yml b/taskfiles/test.yml
--- a/taskfiles/test.yml
+++ b/taskfiles/test.yml
@@ -16,15 +16,36 @@ tasks:
       - go test {{.GO_FLAGS}} -ldflags "{{.LD_FLAGS}}" -timeout 3m -race ./...
 
   integration:
-    desc: Run integration tests
+    desc: Run integration tests for each package with integration tests
     aliases:
       - it
-    prompt:
-      -|
-      WARNING! Running the integration tests in their entirety consumes a huge amount of computing resources and is likely to time out on most machines.
-      It's recommended that you instead run the integration suite for connectors you are working selectively with `go test -run 'TestIntegration/kafka' ./...` and so on.
     cmds:
-      - go test {{.GO_FLAGS}} -ldflags "{{.LD_FLAGS}}" -run "^Test.*Integration.*$$" -timeout 5m ./...
+      - |
+        set -e -o pipefail -u
+        failed=()
+        
+        for pkg in $(find . -name "*integration*_test.go" | xargs dirname | sort -R | uniq)
+        do
+          task test:integration-package PKG="$pkg" || failed+=("$pkg")
+        done
+        
+        if [ ${#failed[@]} -ne 0 ]
+        then
+          echo "FAILED PACKAGES:"
+          printf "  - %s\n" "${failed[@]}"
+          exit 1
+        fi
+    silent: true
+
+  integration-package:
+    desc: Run integration tests for package PKG
+    requires:
+      vars:
+        - PKG
+    vars:
+      TIMEOUT: '{{if .CI}}15m{{else}}5m{{end}}'
+    cmds:
+      - go test {{.GO_FLAGS}} -ldflags "{{.LD_FLAGS}}" -run "^Test.*Integration" -timeout {{.TIMEOUT}} {{.PKG}}
 
   template:
     desc: Run template tests
